version: 2
models:
- name: stg_male_players
  description: Staging for male players with normalized types and snake_case.
  columns:
  - name: gender
    tests:
    - accepted_values:
        arguments:
          values:
            - M
- name: stg_female_players
  description: Staging for female players with normalized types and snake_case.
  columns:
  - name: gender
    tests:
    - accepted_values:
        arguments:
          values:
            - F
- name: stg_male_teams
  description: Staging for male teams.
  columns:
  - name: league_id
    tests:
    - not_null
- name: stg_female_teams
  description: Staging for female teams.
  columns:
  - name: league_id
    tests:
    - not_null
- name: stg_male_coaches
  description: Staging for male coaches.
  columns:
  - name: gender
    tests:
    - accepted_values:
        arguments:
          values:
            - M
- name: stg_female_coaches
  description: Staging for female coaches.
  columns:
  - name: gender
    tests:
    - accepted_values:
        arguments:
          values:
            - F
