CREATE WAREHOUSE ZHOHOLIEVPV_WH
WITH
    WAREHOUSE_SIZE = 'MEDIUM'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    MIN_CLUSTER_COUNT = 1
    MAX_CLUSTER_COUNT = 3
    SCALING_POLICY = 'STANDARD'
    INITIALLY_SUSPENDED = TRUE;

DROP WAREHOUSE IF EXISTS ZHOHOLIEVPV_WH;

SHOW WAREHOUSES;

USE WAREHOUSE ZHOHOLIEVPV_WH;